### ISSUE TITLE
[WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by Paulo-D2000** [tomverbeure/intel_jtag_uart#1]
Installed on Windows 10 x64 using pip, when trying to import I get the error.
QUARTUS_ROOTIR is pointing to the quartus install path...

Images:
![image](https://user-images.githubusercontent.com/58897843/117543225-420c9780-aff2-11eb-8335-38db93f5373e.png)
![image](https://user-images.githubusercontent.com/58897843/117543243-4d5fc300-aff2-11eb-9cc0-6e64c3bd7a9e.png)

Thanks :)

**Comment by tomverbeure** [comment]
The Quartus DLL is a 64-bit library. This error triggers when using a 32-bit version of Python.

Solution: install a 64-bit version of Python.
