### ISSUE TITLE
Usb-BlasterII support ?

### ISSUE THREAD

**Issue by lemmuh** [tomverbeure/intel_jtag_uart#2]
Is the "new" Usb-BlasterII cable also supported ?

I get the error "No UART matching the specified device/instance"

**Comment by tomverbeure** [comment]
The Altera libraries have an abstraction layer that hides the interface details behind a generic API. I can't think of a a reason why a USB-Blaster II wouldn't work, but I don't have one to try it myself.

Have you tried the Quartus System Console? It has the ability to list all the virtual JTAG devices in the system and the JTAG UART should be one of them.

Tom
 (Sorry for not replying earlier: GitHub doesn't send me an email when somebody files an issue in one my repos...)
